42Box/iOS

- iBox/Sources/Web/WebView.swift
- WebView에 progressBar를 추가했습니다.
https://github.com/42Box/iOS/assets/116897060/7e926d41-3d85-4fe9-9952-9c844f483036
> feat: WebView에 progressBar 추가

- Project.swift
- WebView에서 http 연결을 허용했습니다.
- info.plist에 다음과 같은 내용을 추가했습니다.
```
"NSAppTransportSecurity": [
"NSAllowsArbitraryLoadsInWebContent": true
]
```
|Hane 접속 가능|
|---|
|<img width="250" alt="Screenshot 2024-03-19 at 12 58 26 PM" src="https://github.com/42Box/iOS/assets/116897060/5787b71c-829f-4876-be24-202b6921697f">|
> feat: WebView에서 http 연결 허용

- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/Shared/WebCacheManager.swift
- 방문했던 URL에 대한 상태를 기억합니다.
- NSCache를 사용해서 방문했던 WebViewController를 캐싱합니다.
https://github.com/42Box/iOS/assets/116897060/37986edb-22be-4a72-a21f-64e700d500c0
> feat: 방문했던 url 상태 기억

- iBox/Sources/Web/WebView.swift
- WebView에서 ProgressView가 안 보이는 문제를 해결했습니다.
- ProgressView의 위치를 SuperView의 bottom에서 top으로 이동했습니다. (탭바에 가려지는 것으로 추정)
> fix: WebView ProgressView 안 보이는 문제

- iBox/Sources/AppDelegate.swift
- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/BoxList/BoxListViewModel.swift
- iBox/Sources/Settings/Reset/ResetViewController.swift
- iBox/Sources/Shared/CoreDataManager.swift
- iBox/Sources/Shared/UserDefaultsManager.swift
- iBox/Sources/Shared/WebViewPreloader.swift
- 데이터 초기화 시 코어데이터 초기화 적용 
- notification center 이용해 BoxListVIew에 데이터 초기화 알림
- 알림시 BoxListView에서 코어데이터에서 데이터 다시 가져옴
- "iBox" 정확히 쳤을 때만 초기화 확인 버튼 활성화 
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-03-28 at 14 47 43](https://github.com/42Box/iOS/assets/86519350/b0dcb0a4-e6e7-4dd7-8ae1-a1e3752f33e2)|
> feat: reset data

- iBox/Sources/AppDelegate.swift
- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/BoxList/BoxListViewModel.swift
- iBox/Sources/Shared/CoreDataManager.swift
- iBox/Sources/Shared/UserDefaultsManager.swift
- iBox/Sources/Shared/WebViewPreloader.swift
- 즐겨찾기 설정
- 즐겨찾기 북마크 id를 UserDefaults에 저장
- 스와이프에서 즐겨찾기 설정 
- 즐겨찾기 설정/삭제 시 favorite webview reload 
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-03-26 at 21 00 53](https://github.com/42Box/iOS/assets/86519350/bfcb0dff-38bc-4dbe-b615-d79a2b35f99e)|
> feat: set favorite bookmark

- iBox/Sources/Base/BaseViewController.swift
- iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
- iBox/Sources/BoxList/AddBookmark/AddBookmarkViewController.swift
- iBox/Sources/BoxList/AddBookmark/FolderListCell.swift
- iBox/Sources/BoxList/AddBookmark/FolderListView.swift
- iBox/Sources/BoxList/BoxListCell.swift
- iBox/Sources/BoxList/Edit/EditCell.swift
- iBox/Sources/BoxList/EditFolder/EditFolderViewController.swift
- iBox/Sources/BoxList/FolderView.swift
- iBox/Sources/Extension/UIFont+Extension.swift
- iBox/Sources/Settings/HomeTab/HomeTabSelectorCell.swift
- iBox/Sources/Settings/HomeTab/HomeTabSelectorViewController.swift
- iBox/Sources/Settings/Reset/ResetView.swift
- iBox/Sources/Settings/Reset/ResetViewController.swift
- iBox/Sources/Settings/SettingsItemCell.swift
- iBox/Sources/Settings/Theme/ThemeCell.swift
- iBox/Sources/Settings/Theme/ThemeViewController.swift
- Extension을 사용해서 Font를 정의하고 앱 내 폰트를 통일시켰습니다.
|![IMG_7269](https://github.com/42Box/iOS/assets/116897060/2c2cadde-0e40-4e92-b586-f34fbda926f9)|![IMG_7272](https://github.com/42Box/iOS/assets/116897060/38bc1ebc-4fda-425e-a492-016c36d2661f)|
|-|-|
|![IMG_7270](https://github.com/42Box/iOS/assets/116897060/ef3d7065-c5c3-4c05-882a-608bd26d4427)|![IMG_7271](https://github.com/42Box/iOS/assets/116897060/47013f43-c89d-4258-ba34-c0e56bfdb0d1)|
> feat: font 정의

- iBox/Sources/AppDelegate.swift
- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/BoxList/EditFolder/EditFolderCell.swift
- iBox/Sources/BoxList/EditFolder/EditFolderView.swift
- Instruments를 통해 발견한 메모리 누수를 해결합니다.
- BoxListCell, EditFolderCell의 onEdit, onDelete 클로저를 설정해주는 부분에서 cell에 대해 약한 참조를 캡쳐하도록 수정했습니다.
```
cell.onDelete = { [weak self, weak cell] in
guard let self = self, let cell = cell else { return }
if let currentIndexPath = self.tableView.indexPath(for: cell) {
self.delegate?.deleteFolder(at: currentIndexPath)
}
}
cell.onEdit = { [weak self, weak cell] in
guard let self = self, let cell = cell else { return }
if let currentIndexPath = self.tableView.indexPath(for: cell) {
self.editFolderName(at: currentIndexPath)
}
}
```
Instruments에서 메모리 누수가 나지 않는 모습 !
> fix: 클로저 내부에서 cell을 약한 참조로 캡쳐하여 메모리 누수 해결

- iBox/Sources/BoxList/BoxListCell.swift
- iBox/Sources/BoxList/BoxListView.swift
- selection style 적용
- boxlist 에서 didselectrowat 후에 deselect로 변경하여 처리하였습니다.
||
|---|
|![Simulator Screen Recording - iPhone 15 - 2024-04-01 at 19 38 00](https://github.com/42Box/iOS/assets/85754295/64d429e7-893c-4f68-8b8c-a47d7c8ad5ba)|
> fix: set folder selection style#138

- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewModel.swift
- 폴더 이동 후 폴더 터치 이벤트 오류 수정
- 폴더 이동 시 전체 section reload
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-03-28 at 22 35 07](https://github.com/42Box/iOS/assets/86519350/804b8f81-4f15-483e-9741-eac6c5aaf7c3)|
> fix: move folder error

- iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
- iBox/Sources/BoxList/AddBookmark/AddBookmarkViewController.swift
- iBox/Sources/BoxList/AddBookmark/FolderListView.swift
- iBox/Sources/BoxList/AddBookmark/FolderListViewController.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/BoxList/BoxListViewModel.swift
- iBox/Sources/Shared/UserDefaultsManager.swift
- 북마크 추가와 폴더 추가를 메인뷰에 반영
- UserDefaults에 selectedFolderId: UUID?를 저장 
- 북마크 추가, 폴더 추가 시 delegate를 통해 BoxListViewModel에서 처리 
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-03-29 at 02 27 28](https://github.com/42Box/iOS/assets/86519350/cf3ca619-81e8-477b-80f6-3e08b9d66599)|
> feat: add bookmark and folder in main view

- iBox/Sources/Base/BaseViewController.swift
- iBox/Sources/Settings/SettingsViewController.swift
- 모든 탭에 Back Swipe Gesture를 추가합니다.
https://github.com/42Box/iOS/assets/116897060/3983e0c8-f20e-437a-8593-06530e0eec57
> feat: Back Swipe Gesture 추가

- iBox/Sources/BoxList/BoxListView.swift
- 꾹 누르면 미리보기
- context menu 사용하였습습니다.
|조금 기다려주시면 gif 나옵니다.|
|---|
|![Simulator Screen Recording - iPhone 15 - 2024-04-01 at 21 07 39](https://github.com/42Box/iOS/assets/85754295/331d04e2-3c65-43f2-9bf6-6be16684bb31)|
> feat: context menu preview

- iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
- iBox/Sources/BoxList/AddBookmark/FolderListCell.swift
- iBox/Sources/BoxList/BoxListCell.swift
- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/EditFolder/EditFolderCell.swift
- iBox/Sources/BoxList/FolderButton.swift
- iBox/Sources/BoxList/FolderView.swift
- 폴더, 북마크 이름 라벨의 leading, trailing을 설정하여 셀을 넘어가지 않도록 하였습니다. 
- 폴더 이름 오토레이아웃 변경 (FolderView, FolderButton, EditFolderCell)
- 북마크 이름 오토레이아웃 변경 (BoxListCell)
- 북마크 추가화면에서 폴더이름 오토레이아웃 변경 (AddBookmarkView, FolderListCell)
||
|---|
|![edit_layout](https://github.com/42Box/iOS/assets/86519350/1bcda6a6-d2ae-4bee-92b3-f7efa52b6248)|
> feat: set folder,bookmark name label trailing

- iBox/Sources/AppDelegate.swift
- iBox/Sources/Favorite/FavoriteView.swift
- 즐겨찾기 미리로드 설정
- 미리로드 시 앱 시작할 때 즐겨찾기 웹뷰 로드
- 미리로드 해제 시 FavoriteView 로드될 때 즐겨찾기 웹뷰 로드
> feat: set favorite preload

- iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
- iBox/Sources/BoxList/AddBookmark/FolderListCell.swift
- AddBookmarkView 내 responder 설정 및 리팩토링
- 북마크 추가화면 내 textView의 키보드 타입을 emailAddress 타입으로 변경했습니다.
- 북마크 추가화면 내 '목록' 버튼 label 의 width 제약을 삭제 및 선택된 폴더 label 제약을 재설정 했습니다.
- 북마크 추가화면 내 FolderListView의 FolderListCell에서 folderNameLabel 제약을 수정했습니다.
- 북마크 추가화면 내 textField 의 top 제약을 수정했습니다.
- 북마크 추가화면 내 키보드 responder 설정 및 자동보정을 비활성화 했습니다. 
- 선택된 폴더 label 제약 수정 이전
- 선택된 폴더 label 제약 수정 이후
- FolderListCell의  folderNameLabel 제약 수정 이전
- FolderListCell의  folderNameLabel 제약 수정 이후
- textField 의 top 제약을 수정 이전
- textField 의 top 제약을 수정 이후
- 자동보정 비활성화 이전
https://github.com/42Box/iOS/assets/116494364/a3acf918-7c13-4a27-8e16-522540633d12
- 자동보정 비활성화 이후
https://github.com/42Box/iOS/assets/116494364/1d1eff33-d203-46d2-a8d1-212af3b0a65e
- 키보드 responder 설정 …
> feat: set responder in AddBookmarkView/#156

- iBox/Sources/Shared/WebViewPreloader.swift
- iBox/Sources/Web/WebView.swift
- 동영상이 전체 화면이 아닌 inline으로 실행 가능하도록 함
- WKWebVIew configuration 설정 - allowsInlineMediaPlayback
> feat: 동영상 자동재생 막기

- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/Main/MainTabBarController.swift
- iBox/Sources/Model/SettingsItem.swift
- iBox/Sources/Settings/SettingsView.swift
- iBox/Sources/Settings/SettingsViewModel.swift
- iBox/Sources/Shared/UserDefaultsManager.swift
- 진동 효과를 추가하고, 진동 효과를 켜고 끌 수 있는 스위치를 설정 화면에 추가합니다.
- 폴더, 탭바 탭 : 약한 진동
- 북마크/폴더 추가/삭제, 즐겨찾기 설정, 공유 : 부드러운 진동
|<img width="300" alt="Screenshot 2024-03-14 at 5 35 42 AM" src="https://github.com/42Box/iOS/assets/116897060/082446ed-8ad6-4bfe-8d08-00c6f7d8b56d">|
|-|
> feat: 진동 추가

- iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
- 북마크 추가화면 내 북마크 이름을 입력하는 nameTextView에 clearButton을 추가하였습니다.
- textViewDidChange 내에서 nameTextView.text.isEmpty 에 따라 clearButton.isHidden 을 설정합니다.
- ShareExtension으로 nameTextView.text가 채워진 경우 updateTextField 함수에서 clearButton.isHidden을 설정합니다.
|||
|---|---|
|||
https://github.com/42Box/iOS/assets/116494364/79dd7781-c29a-4bf9-b947-dbb1aebc0681
https://github.com/42Box/iOS/assets/116494364/b2eefdbf-9d17-4561-988b-3554f1b95656
> feat: Add clearButton in nameTextView

- iBox/Sources/Web/WebView.swift
- 웹뷰 내 로딩을 추적합니다.
- 기존에는 초기 페이지 로드 시에만 프로그레스 바가 표시되었지만, 이제 웹뷰 내에서 다른 페이지로의 이동 시에도 로딩을 추적하여 보여줍니다.
- 웹 콘텐츠의 로딩 상태에 따라 프로그레스 바의 가시성과 진행 상황을 업데이트하기 위해 추가 WKNavigationDelegate 메소드를 구현했습니다.
https://github.com/42Box/iOS/assets/116897060/6d90f055-de1c-40aa-86d4-b2756c3bd51d
> feat: 웹뷰 내 로딩 추적

- Project.swift
부모 앱(iBox)과 앱 확장(ShareExtension)의 번들 버전(`CFBundleShortVersionString`)이 서로 일치하지 않아 발생한 문제입니다. 이로 인해 Xcode가 앱 확장을 부모 앱의 일부로 정확히 인식하지 못하고 있었습니다.
- `Project.swift`의 `infoPlist` 부분에서 부모 앱(iBox) 및 앱 확장(ShareExtension)의 `CFBundleShortVersionString` 값을 "**1.0.0**"으로 일치시켰습니다.
> fix: Command ValidateEmbeddedBinary failed 문제 해결

- iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
- AddBookmarkView 내 textView 키보드 타입 변경
- AddBookmarkView 내 nameTextView 의 키보드를 defualt타입으로 변경하였습니다.
- AddBookmarkView 내 urlTextView 의 키보드를 URL타입으로 변경하였습니다.
https://github.com/42Box/iOS/assets/116494364/a6f7ef3c-14b1-4728-977d-df1c4c2ab11e
> feat: textView 키보드 타입 변경

- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/Extension/UIColor+Extension.swift
- iBox/Sources/Extension/UIFont+Extension.swift
- iBox/Sources/Web/RefreshControl.swift
- iBox/Sources/Web/WebView.swift
- iBox/Sources/Web/WebViewController.swift
- 커스텀 리프레시 컨트롤 추가
- `북마크 추가`, `새로 고침`, `처음으로 이동`의 3가지 행동을 할 수 있는 커스텀 리프레시 컨트롤을 추가합니다.
https://github.com/42Box/iOS/assets/116897060/6d965056-67d0-445d-a0e9-f6d8ea6af7bb
<details><summary>안습 (배경 색상 설정해서 해결 !)</summary>
<p>
|![IMG_7513](https://github.com/42Box/iOS/assets/116897060/5146b94b-c6eb-48a8-990e-08d52837f210)|![IMG_7514](https://github.com/42Box/iOS/assets/116897060/559cb863-afad-47c1-9c19-6c269fdf3f60)|![IMG_7515](https://github.com/42Box/iOS/assets/116897060/3f25c7ac-1737-4e62-b322-4e2058f2bcdb)|
|-|-|-|
</p>
</details>
> feat: add custom refresh control

- iBox/Sources/Shared/WebViewPreloader.swift
- favoriteView에서 back gesture
- allowsBackForwardNavigationGestures = true 설정 
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-09 at 15 41 17](https://github.com/42Box/iOS/assets/86519350/d9311c2e-2dcc-426c-af7d-ae14370ce33e)|
> feat: back gesture in favorite view

- iBox/Sources/Web/WebView.swift
- "새 창으로 열기" 옵션이 설정된 (`target="_blank"`) 링크를 웹뷰 내부에서 열기 위해 WKNavigationDelegate에 함수를 구현했습니다.
``` javascript
func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void) {
// "새 창으로 열기" 링크 WebView 내에서 열기
if navigationAction.targetFrame == nil {
webView.load(navigationAction.request)
}
decisionHandler(.allow)
}
```
> feat: 새 창으로 열기 옵션 링크 내부에서 열기

- iBox/Sources/BoxList/AddBookmark/FolderListCell.swift
- FolderListCell 내 checkmark 사이즈를 변경.
- UIImage.SymbolConfiguration 를 통해 checkmark 이미지 구성을 변경하였습니다.
|변경전|변경후|
|---|---|
|![Simulator Screenshot - iPhone 15 Pro - 2024-04-16 at 00 08 26](https://github.com/42Box/iOS/assets/116494364/b917bbea-1246-41a1-95e9-b72b4af0d36e)|![Simulator Screenshot - iPhone 15 Pro - 2024-04-16 at 00 05 54](https://github.com/42Box/iOS/assets/116494364/7d25e7d0-80e4-4cf3-9d2a-c036c0a07579)|
> refactor: FolderListCell 내 checkmark 변경

- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/BoxList/BoxListViewModel.swift
- iBox/Sources/BoxList/FolderButton.swift
- 폴더 꾹 누르면 편집/삭제 기능 
- 폴더 버튼에 menu 추가 (edit action, delete action)
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-16 at 14 56 42](https://github.com/42Box/iOS/assets/86519350/d144e471-9090-428d-a130-8f772447f085)|
> feat: folder menu in boxList

- iBox/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox0.imageset/Contents.json
- iBox/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox1.imageset/Contents.json
- iBox/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox2.imageset/Contents.json
- iBox/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox3.imageset/Contents.json
- iBox/Sources/BoxList/AddBookmark/AddBookmarkView.swift
- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/BoxList/FolderButton.swift
- iBox/Sources/Extension/UIFont+Extension.swift
- iBox/Sources/Extension/UIImage+Extension.swift
- 폴더가 없을 때 라벨 보여줌
- 폴더 옆 버튼 크기 수정
- emptyStackView(emptyLabel, emptyImageView)를 folder 있을 때 isHidden = false
- 폴더버튼 size 수정
|emptyStackView|폴더버튼|
|---|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-11 at 18 14 06](https://github.com/42Box/iOS/assets/86519350/c93c0e46-182e-4fe2-96b9-e93fca5b3411)|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-11 at 18 12 24](https://github.com/42Box/iOS/assets/86519350/aeb6ebaa-fb43-4eef-943e-c84f57b5b43a)|
> feat: empty folder label

- iBox/Sources/Settings/SettingsItemCell.swift
- SettingsItemCell의 chevron 버튼 영역이 터치가 안 되는 문제를 해결합니다.
- chevron 버튼의 `isUserInteractionEnabled` 속성을 false로 지정합니다.
> fix: SettingItemCell chevron 버튼 터치 안 되는 문제 해결

- iBox/Sources/BoxList/BoxListView.swift
- BoxListView에서 폴더 버튼을 꾹 누를 때 진동 효과를 추가했습니다.
> feat: 폴더 버튼 꾹 누를 때 진동 추가

- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewModel.swift
- 북마크 이동시 순서가 바뀌는 오류 수정 
- tableView(_:moveRowAt:to:)에서 같은 섹션 내에서 row 아래로 옮길 때 로직 추가
|before|after|
|---|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-16 at 22 25 54](https://github.com/42Box/iOS/assets/86519350/debfb3c4-b6eb-4b52-9839-09a5aabf1c05)|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-16 at 22 26 36](https://github.com/42Box/iOS/assets/86519350/09a6681f-513b-4de8-acb5-bce7b8d94789)|
> fix: bookmark move error

- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewModel.swift
- iBox/Sources/Favorite/FavoriteView.swift
-  폴더 열거나 닫을 때 scroll 조절 
- estimatedSectionHeaderHeight, estimatedSectionFooterHeight, estimatedRowHeight = 0으로 설정해 원하지 않던 스크롤 동작 없앰 (https://developer.apple.com/forums/thread/86703)
- 폴더 열때 해당 section으로 scrollToRow
|before|after|
|---|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-16 at 23 06 33](https://github.com/42Box/iOS/assets/86519350/d5fac26f-a830-4c16-bd26-26b7d4e2a83f)|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-16 at 23 07 46](https://github.com/42Box/iOS/assets/86519350/df2294f4-a47b-4feb-8bbb-cdf252871288)|
> Dev/194 feat folder open시 해당 폴더로 스크롤/#194

- ShareExtension/Sources/ShareViewController.swift
- iBox/Sources/Shared/AddBookmarkManager.swift
- iBox/Sources/Web/WebViewController.swift
- URL encoding과 decoding 관련 수정.
- 여러 개의 쿼리 파라미터가 있는 url의 경우 첫 번째를 제외한 나머지 쿼리 파라미터가 전달이 안되는 부분을 수정하였습니다.
- ShareExtension시 url에 한글이 들어 있는 경우 북마크 추가 화면에 글자가 깨져서 들어오는 부분을 수정하였습니다.
https://github.com/42Box/iOS/assets/116494364/7495bb65-7898-4c29-b591-a2c927321838
> fix: url encoding decoding 관련 수정

- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/Shared/WebCacheManager.swift
- 꾹 누르면 북마크 편집 
- ^^
||
|---|
|![Simulator Screen Recording - iPhone 15 - 2024-04-17 at 01 17 48](https://github.com/42Box/iOS/assets/85754295/7941ebc1-0a64-4302-a46e-608806d81690)|
> feat: context edit bookmark

- iBox/Sources/BoxList/BoxListView.swift
- 이름에 이모티콘 있을 때 불필요한 애니메이션
- setEditing의 animation 없앰 
|before|after|
|---|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-17 at 15 47 37](https://github.com/42Box/iOS/assets/86519350/2b622fc6-2303-4eea-a0ab-0c4fed5c0596)|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-17 at 15 48 31](https://github.com/42Box/iOS/assets/86519350/d9d540e3-cc06-42b1-b0cf-371a3aa3edb7)|
> fix: bookmark 편집시 애니메이션 수정

- iBox/Sources/AddBookmark/AddBookmarkView.swift
- iBox/Sources/AddBookmark/AddBookmarkViewController.swift
- iBox/Sources/AddBookmark/FolderListViewController.swift
- FolderListViewController에 제스처를 통한 뒤로 가기를 허용하는 기능을 추가했습니다.
``` Swift
navigationController?.interactivePopGestureRecognizer?.delegate = self
```
+clearButton 터치 시 nameTextView를 firstResponder로 설정합니다.
https://github.com/42Box/iOS/assets/116897060/6dfd3a26-0dcc-4d76-8466-fb47151e429c
> feat: FolderListViewController에 백 제스처 허용

- iBox/Sources/BoxList/BoxListView.swift
- 라이트모드/다크모드에 따른 여우 색깔 적용 
- traitCollectionDidChange에서 모드 변경 감지
|before|after|
|---|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-17 at 18 30 58](https://github.com/42Box/iOS/assets/86519350/dcd55516-b837-48ec-bae2-36b4c65a3311)|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-17 at 18 29 47](https://github.com/42Box/iOS/assets/86519350/3152c4ec-ca76-4d93-ac4b-cdc8c0fea57e)
|
> fix: 폴더 비었을 때 모드에 따른 여우 색 변경

- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/Extension/UIViewController+Extension.swift
- 이미 present된 view가 있는 경우 ShareExtension시 북마크 추가화면이 뜨지 않는 버그 수정.
- ShareExtension 시 현재 뷰 컨트롤러가 AddBookmarkViewController이지 않은 경우 현재 모달을 dismiss 후 addButtonTapped() 메서르를 호출합니다. 
https://github.com/42Box/iOS/assets/116494364/61d95c58-8ffe-4ad5-b3e5-67e175dbcfb9
> fix: ShareExtension시 present 되어 있는 view가 있는 경우 버그 수정

- iBox/Sources/AddBookmark/AddBookmarkViewController.swift
- 북마크 추가 시 사용자가 입력한 url에 https:// 와 http:// 가 둘 다 없는 경우 https:// 를 추가
- 북마크 추가 시 사용자가 입력한 url에 대소문자 포함 https:// 혹은 http:// 이 존재하지 않는 경우 '추가' 버튼을 누르면 https:// 를 추가해주는 기능을 구현했습니다.
https://github.com/42Box/iOS/assets/116494364/66e2d578-fd46-430d-b959-3763bca2242e
> feat: 사용자가 입력한 URL에 https://가 없을 경우 자동으로 추가하는 기능 구현

- iBox/Sources/BoxList/BoxListView.swift
- 셀 지웠을 때 애니메이션 오류 수정 
- previewForDismissingContextMenuWithConfiguration 에서 background clear로 설정
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-18 at 16 29 42](https://github.com/42Box/iOS/assets/86519350/33cf9b54-15bf-4b92-bdb9-832e1a2cd4cf)|
> fix: cell remove animation

- Project.swift
- Tuist/Dependencies.swift
- iBox/Sources/AddBookmark/AddBookmarkView.swift
- iBox/Sources/AddBookmark/AddBookmarkViewController.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/Extension/UIViewController+Extension.swift
- iBox/Sources/Model/BookmarkError.swift
- iBox/Sources/Shared/AddBookmarkManager.swift
- 쉐어익스텐션/북마크 추가에서 url fetching 중 skeletonView 추가
- 해당 textview에 skeletonable 추가 
- fetching 여부 알려주는 isFetching 변수 추가
- fetching 중 오류 시 alert
|성공|실패|
|---|---|
|![success](https://github.com/42Box/iOS/assets/86519350/a68e8425-0ac3-4b6a-976d-e264a244bd11)|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-21 at 22 15 23](https://github.com/42Box/iOS/assets/86519350/58d8869b-8a54-41bc-beb2-d62db1263d96)|
> feat: loading 중 skeletonview

- iBox/Sources/Error/ErrorPageView.swift
- iBox/Sources/Error/ErrorPageViewController.swift
- iBox/Sources/Web/WebView.swift
- iBox/Sources/Web/WebViewController.swift
- errorpage의 business logic을 완성하였습니다.
- errorpage view 작업 중 입니다.
- 책임 분리 원칙에 따라 error page의 delegate를 error page view controller가 지니게 하였습니다.
||
|---|
|![image](https://github.com/42Box/iOS/assets/85754295/864ecb35-9c89-43dc-b968-991c21469a61)|
> feat: webview error page/#225

- Project.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/Model/SettingsItem.swift
- iBox/Sources/Settings/Guide/GuideView.swift
- iBox/Sources/Settings/Guide/GuideViewController.swift
- iBox/Sources/Settings/HomeTab/HomeTabSelectorViewController.swift
- iBox/Sources/Settings/SettingsViewController.swift
- iBox/Sources/Settings/SettingsViewModel.swift
- iBox/Sources/Web/WebView.swift
- 전반적으로 소소한 수정을 했습니다 ...
- 설정 아이템 이름을 `홈 화면`에서 `시작 화면`으로 변경했습니다.
|스크린샷1|스크린샷2|
|-|-|
|![IMG_7739](https://github.com/42Box/iOS/assets/116897060/9998976a-8c1c-4060-ab34-7a1ca17c2467)|![IMG_7740](https://github.com/42Box/iOS/assets/116897060/0a79ff74-7ab5-4d3e-8809-9a47bf0d1b98)|
- 웹뷰 프로그레스바 색상을 `.box2`로 변경했습니다.
|라이트 모드|다크 모드|
|-|-|
|![IMG_7741](https://github.com/42Box/iOS/assets/116897060/37a359fd-a8f5-4450-8f43-2c2ed0b09bfc)|![IMG_7742](https://github.com/42Box/iOS/assets/116897060/73dd01bc-6885-489d-a0b0-6cb9d1bbed8f)|
- 빌드 타겟을 iPhone으로 변경했습니다.
> feat: 소소한 수정

- iBox/Sources/Shared/AddBookmarkManager.swift
- 쉐어익스텐션/북마크 추가에서 http가 들어온 경우 바로 url만 입력되도록 수정
- http:// 들어온 경우 따로 처리
||
|---|
|![fixHttp](https://github.com/42Box/iOS/assets/86519350/678cd5c1-bd6f-490d-ad01-7242c2a3eb56)|
> fix: http url 처리

- iBox/Sources/AppDelegate.swift
- iBox/Sources/Favorite/FavoriteView.swift
- iBox/Sources/Favorite/FavoriteViewController.swift
- iBox/Sources/Model/SettingsItem.swift
- iBox/Sources/Settings/SettingsView.swift
- iBox/Sources/Settings/SettingsViewModel.swift
- iBox/Sources/Shared/UserDefaultsManager.swift
- iBox/Sources/Web/RefreshControl.swift
- 즐겨찾기 미리로드 없앰
- webview 로딩 지연 없앰
- setting에서 preload 삭제 
- appdelegate에서 webview 로드해서 처음 로드할 때 지연 해결 (https://stackoverflow.com/questions/74301868/wkwebview-ios-slow-on-first-launch)
||
|---|
|<img width=300 src="https://github.com/42Box/iOS/assets/86519350/4bff04e0-4d47-44a6-9622-5abc7eb66ee7">|
> feat: remove preload

- iBox/Sources/AddBookmark/AddBookmarkViewController.swift
- 북마크 url에 # 그대로 처리
- addingPercentEncoding의 allowed character에 "#" 추가 
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-24 at 15 19 41](https://github.com/42Box/iOS/assets/86519350/b9c89866-0d45-4ab1-84df-66a2adbd784f)|
> fix: 북마크 추가 시 url 안에 있는 # 그대로 처리

- Project.swift
- ShareExtension/Sources/ShareViewController.swift
- youtube 등 외부 애플리케이션에서의 extension items 들을 처리하였습니다.
- plist
- extension context 처리
|||
|---|---|
|||
> fix: 외부 application extension item 처리/#229

- iBox/Sources/Error/ErrorPageView.swift
- ErrorPageView의 레이아웃을 수정합니다.
- 중복된 제약사항 설정을 제거했습니다.
- 폰트를 설정했습니다.
|URL 짧을 때|URL 길 때|
|-|-|
|![IMG_7786](https://github.com/42Box/iOS/assets/116897060/034a809d-7cb6-4b0f-a082-31c2b08eae12)|![IMG_7787](https://github.com/42Box/iOS/assets/116897060/13203d11-7c77-45ac-b63f-c742b91e5ed8)|
> style: ErrorPageView 레이아웃 수정

- iBox/Sources/BoxList/BoxListViewController.swift
- iBox/Sources/BoxList/EditFolder/EditFolderViewController.swift
- 아이패드에서 UIAlertController를 present할 때 에러가 나는 문제를 해결합니다.
- UIAlertController의 prefferedStyle을 .actionSheet에서 .alert로 변경했습니다.
|변경 전|변경 후|
|-|-|
|![IMG_7784](https://github.com/42Box/iOS/assets/116897060/e0f0c894-171b-4fd1-879d-9260cbf2444a)|![IMG_7785](https://github.com/42Box/iOS/assets/116897060/c1f7a904-1da8-4198-8130-eaa99a97b195)|
> fix: 아이패드 대응 UIAlertConteollr preferredStyle 수정

- .gitignore
- iBox/Sources/Web/WebView.swift
- web view 안에서 새 창 이동 안되는 경우 처리
- webView(_:createWebViewWith:for:windowFeatures:) 함수 내에서 처리
||
|---|
|![Simulator Screen Recording - iPhone 15 Pro - 2024-04-27 at 00 20 58](https://github.com/42Box/iOS/assets/86519350/4a3f8dbe-14aa-4ba9-937d-69752d877e5f)|
> fix: web view 안에서 새 창 이동 안되는 경우 처리

- iBox/Sources/BoxList/BoxListViewModel.swift
- 데이터 받아온 후 boxlist에서 나타나지 않는 에러 고침
- viewDidLoad에서 데이터 가져온 후 UI 업데이트
> fix: boxlist load 후 적용

- iBox/Sources/Initializer/DefaultData.swift
- iBox/Sources/Initializer/DefaultDataModel.swift
- iBox/Sources/Settings/Reset/ResetViewController.swift
- defaultFolders url이 없는 경우 폴더를 생성하지 않음.
- https://42box.github.io/iOSHowToUse/ 로 how to use 를 변경하고 favorite view에 적용시켰습니다.
- DefaultDataLoader.defaultURL
- DefaultDataLoader.defaultData
||
|---|
|![image](https://github.com/42Box/iOS/assets/85754295/5be2dbb4-1266-4d2f-ae3c-68ac62ea0c68)|
> fix: defaultFolders url이 없는 경우 폴더를 생성하지 않음.

- Project.swift
- README.md
- iBox/Sources/Initializer/DefaultData.swift
- iBox/Sources/Initializer/DefaultDataModel.swift
- iBox/Sources/Settings/Reset/ResetViewController.swift
- 1.0.2 버전으로 update 합니다. 
- [fix: defaultFolders url이 없는 경우 폴더를 생성하지 않음.](https://github.com/42Box/iOS/commit/73ada20f5c780d7b2da71cd889a141a2e880199e)
- [chore: iBox to 42Box](https://github.com/42Box/iOS/pull/277/commits/b531153caa8442635430b067e5ed39c70f541a46)
> Main Version 1.0.2 🦊

- iBox/Sources/BoxList/BoxListView.swift
- iBox/Sources/BoxList/BoxListViewController.swift
- 아이패드에서 공유 기능이 작동하지 않는 문제를 해결합니다.
- popover가 표시될 위치(`sourceView`, `sourceRect`)를 지정합니다.
> fix: 아이패드 대응 UIActivityViewController popover 설정

- iBox/Sources/AddBookmark/AddBookmarkView.swift
- iBox/Sources/AddBookmark/AddBookmarkViewController.swift
- 북마크 추가 시 폴더 목록이 없을 때, 사용자 경험 개선을 위해 색상을 추가합니다.
|폴더 목록 없음|폴더 목록 있음|
|-|-|
|![IMG_7869](https://github.com/42Box/iOS/assets/116897060/0c9542df-6062-4674-8f8b-2a678a720878)|![IMG_7870](https://github.com/42Box/iOS/assets/116897060/7b465d40-913e-40e9-9e38-fe4b9467f609)|
> feat: 북마크 추가 시 폴더 없을 때 색상 추가
